version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ems-frontend
    ports:
      - "8444:443"
      - "8080:80"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    environment:
      - VITE_API_URL=https://ems-backend:8443
    networks:
      - ems-network

networks:
  ems-network:
    external: true
